### ISSUE TITLE
ValueError: Sensor sensor.weather_pollen_levels has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Moderate' (<class 'str'>)

### ISSUE THREAD

**Issue by codyc1515** [ciejer/metservice-weather#24]
## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1381
Downloaded Repositories | 19
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | beta
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 13.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Silicon Labs Multiprotocol (2.4.3), MariaDB (2.6.1), Calibre (7.3.0), ESPHome (2023.12.5), File editor (5.7.0), Node-RED (17.0.2), Samba share (12.2.0), Scrypted (18-jammy-full.s6-v0.80.0), Tailscale (0.14.0), Terminal & SSH (9.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 10, 2024 at 23:52
-- | --
current_recorder_run | January 13, 2024 at 10:14
estimated_db_size | 45.67 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Xiaomi Miot Auto</summary>

error | failed to load: timeout
-- | --

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

```
Logger: homeassistant
Source: components/sensor/__init__.py:646
First occurred: 14:37:46 (1 occurrences)
Last logged: 14:37:46

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 644, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Moderate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/metservice_weather/sensor.py", line 141, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state
    raise ValueError(
ValueError: Sensor sensor.weather_pollen_levels has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Moderate' (<class 'str'>)
```

### Reproduction steps

1. Pollen Type is Moderate

**Comment by ciejer** [comment]
Hey @codyc1515 - is this fixed by your pr #22? I was unable to recreate.

**Comment by codyc1515** [comment]
Oh, yes.

**Comment by codyc1515** [comment]
So the pollen sensors are a bit of an oddity in that they don't exist 100% of the time, despite being reasonably important.

I'm not sure why it sometimes disappears but the integration failed previously when the pollen data was no longer showing on the MetService website. It's showing for Auckland right now but check tomorrow - it could be gone.

In the past, the Pollen forecast was a sponsored forecast co-branded with one of the big hay fever medication brands, similar to how The Warehouse's BBQ Forecast, PlaceMakers Tradies Forecast and Harvey Norman's Laundry Drying Time work.

Despite all of the above, Pollen has never shown in the app (despite The Warehouse, PlaceMakers & HN all do).

Perhaps they bought it back by popular demand - who knows?

![image](https://github.com/ciejer/metservice-weather/assets/50791984/45ad91ea-ed1c-44c0-96a2-ef8179c8384f)
