### ISSUE TITLE
Error while setting up metservice_weather platform for weather

### ISSUE THREAD

**Issue by teamsuperpanda** [ciejer/metservice-weather#29]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.70-haos
arch | x86_64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4746
Installed Version | 1.34.0
Stage | running
Available Repositories | 1379
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 21, 2024 at 12:00 PM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
certificate_status | ready
instance_id | a902d669ad09429ca2b58d08bdde4669
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 33.7 GB
disk_used | 9.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.12.9), Node-RED (17.0.3), Samba share (12.2.0), File editor (5.7.0), Terminal & SSH (9.8.1), Mosquitto broker (6.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 20, 2024 at 12:35 AM
-- | --
current_recorder_run | January 29, 2024 at 11:16 AM
estimated_db_size | 182.21 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 3 / 4
local_online | 0 / 0

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:368
Integration: Weather (documentation, issues)
First occurred: 11:16:41 AM (2 occurrences)
Last logged: 11:17:20 AM

Error while setting up metservice_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 729, in state_attributes
    if (humidity := self.humidity) is not None:
                    ^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 260, in humidity
    return int(self.coordinator.get_current_public(FIELD_HUMIDITY))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### Reproduction steps

1. Installed the integration just fine and selected Auckland - entities populated
2. Removed integration and restarted
3. Selected my actual town and now get this error

I've deleted the integration, restarted, added it again but it won't poll and entities are unknown.

**Comment by teamsuperpanda** [comment]
It fails when I select Kumeu. Selected Waitakere and get some info but missing tides.

**Comment by ciejer** [comment]
Hey @teamsuperpanda - looks like Metservice's rural areas have a much more limited set of data available (including a complete lack of current observations, and a few things moved around)
It's now working on mine - try updating to v0.3.1

**Comment by teamsuperpanda** [comment]
Thanks mate! Geez you work fast huh!

**Comment by ciejer** [comment]
I knew I'd get bugs found when it went live on HACS, didn't expect one within 4 hours! Been waiting since October for that approval :)
I'm just finishing off a recursion function to deal with Metservice's inconsistent api structure between cities (and especially between their ad partners!) - this should be way more stable.
Just released as v0.4.0.

cc @codyc1515 - the new `get_from_dict` approach means public api should be just as stable as mobile, and includes a couple more sensors.
