### ISSUE TITLE
weather.get_forecasts based template sensor returns bad timedate

### ISSUE THREAD

**Issue by droopanu** [ciejer/metservice-weather#33]
### System Health details

skip

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When creating a template sensor to hold the whole forecast in an attribute, it ends up with a broken json.
It works for OpenWeatherMap and Accuweather

### Reproduction steps

1. Configure the MetService and OpenWeatherMap integrations 
2. Create a trigger-based template to extract the forecast from these entities into an attribute:
`  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
      - platform: event
        event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.openweathermap
        response_variable: hourly
    sensor:
      - name: OpenWeatherMap Forecast Hourly
        unique_id: OpenWeatherMap_forecast_hourly
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly['weather.openweathermap'].forecast }}"`

`  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
      - platform: event
        event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.the_villa_metservice
        response_variable: hourly
    sensor:
      - name: MetService Weather Forecast Hourly
        unique_id: metservice_forecast_hourly
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly['weather.the_villa_metservice'].forecast }}"`

3.  Check the attributes in the Developer Tools/States:
![image](https://github.com/ciejer/metservice-weather/assets/7566514/4e1165e0-8396-4bb3-9709-a30f727cbe8b)
![image](https://github.com/ciejer/metservice-weather/assets/7566514/9284f7dd-0a8e-4f86-a629-4555c8cad5fa)

5. 
6.
...

**Comment by ciejer** [comment]
Resolved in #34, released in v0.4.1 - thanks for highlighting!
