### ISSUE TITLE
Add Fire Season/Danger information

### ISSUE THREAD

**Issue by seanmccabe** [ciejer/metservice-weather#35]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not a problem, just a general wish.

### Describe the solution you'd like

Add the fire season and fire danger information.

![image](https://github.com/ciejer/metservice-weather/assets/12243212/32351c60-0600-4858-8832-6a5d915eab63)

### Describe alternatives you've considered

Web scraper.

### Additional context

Thanks so much, I was trying for ages to get the drying time using a scraper, and had given up!

**Comment by ciejer** [comment]
Morning @seanmccabe !
Check out v0.5.0 - have added these two sensors.

**Comment by seanmccabe** [comment]
Awesome @ciejer job well done and thanks again :)
