### ISSUE TITLE
No 'Next X Tide' info usign public API

### ISSUE THREAD

**Issue by clowgg** [ciejer/metservice-weather#41]
[### System Health details

## System Information

version | core-2024.2.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1385
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 4, 2025 at 1:00 PM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | ap-southeast-1-2.ui.nabu.casa
certificate_status | ready
instance_id | e38287e14dd74dc3aa3d5d2e86273523
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 16.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), AirCast (4.2.0), Advanced SSH & Web Terminal (17.1.0), TasmoAdmin (0.29.1), Mosquitto broker (6.4.0), OneDrive Backup (2.3), Zigbee2MQTT (1.35.3-1), chrony (3.0.1), ESPHome (2023.12.9), Whisper (1.0.2), Piper (1.4.0), openWakeWord (1.8.2), Run On Startup.d (0.11a)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 9
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 29, 2024 at 4:17 AM
-- | --
current_recorder_run | February 8, 2024 at 10:36 AM
estimated_db_size | 681.98 MiB
database_engine | sqlite
database_version | 3.44.2

</details>](url)

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have selected Auckland as my city,. 
There is no tide information showing up:

![image](https://github.com/ciejer/metservice-weather/assets/145304547/88f37789-4387-4432-a73f-523c8168870f)

Is that a bug, or am I missing some configuration?

### Reproduction steps

1.
2.
3.
...

**Comment by Tarawera** [comment]
It is the same for me using Public location of Nelson.

**Comment by ciejer** [comment]
Evening @clowgg and

**Comment by Tarawera** [comment]
Yes that would be useful. Thanks.

**Comment by ciejer** [comment]
Updated in v0.6.0 - please update and let me know what you think @Tarawera @clowgg 

Note - this is a breaking change; you'll need to reconfigure the integration to choose your tide locations.

**Comment by Tarawera** [comment]
Thanks ChrisAll is working fine in Nelson now. I did have to delete and reinstall the integration to get it to ask about the tide city.RegardsDavid (Tarawera)On 17/02/2024, at 2:33 PM, Chris Jenkins ***@***.***> wrote:﻿
Updated in v0.6.0 - please update and let me know what you think @Tarawera @clowgg
Note - this is a breaking change; you'll need to reconfigure the integration to choose your tide locations.

**Comment by clowgg** [comment]
Deleted and re-added integration in HA [Settings/Integrations] (http://ha/config/integrations/integration/metservice_weather).
Choose Onehunga as tide locale. All working fine :)  Thank you @ciejer !!!

![image](https://github.com/ciejer/metservice-weather/assets/145304547/8af05446-4a5f-4ff2-b2ba-48024b8fc23e)
