### ISSUE TITLE
Some sensors not working

### ISSUE THREAD

**Issue by Krispkiwi** [ciejer/metservice-weather#43]
## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 11.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.1.0), Studio Code Server (5.15.0), Samba share (12.3.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), RPC Shutdown (2.4), ESPHome (2023.12.9), Cloudflared (5.1.3), Zigbee2MQTT (1.35.3-1), ADB - Android Debug Bridge (0.7.0), MQTT Explorer (browser-1.0.3), Node-RED (17.0.7), Vaultwarden (Bitwarden) (0.21.1), Uptime Kuma (0.12.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 12, 2024 at 11:55 AM
-- | --
current_recorder_run | February 14, 2024 at 2:41 AM
estimated_db_size | 46.94 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Some sensors like wind information, temperature and pressure haven't been working for me since around the latest core update using public - dunedin

### Reproduction steps

Installation on the latest HA
Install metservice

**Comment by ciejer** [comment]
Hi @Krispkiwi ,
I've just updated my dev container to that HA version, no issues with Dunedin - can you please confirm you're still having issues?
Please also try a reconfig; preferably after installing latest version 0.6.0 which will need a reconfig to get the new tide functionality anyway.

Thanks! -Chris

**Comment by Krispkiwi** [comment]
> Hi @Krispkiwi , I've just updated my dev container to that HA version, no issues with Dunedin - can you please confirm you're still having issues? Please also try a reconfig; preferably after installing latest version 0.6.0 which will need a reconfig to get the new tide functionality anyway.
> 
> Thanks! -Chris

Just downloaded, it appears to be working better. One thing i noticed was metservice wasn't uploading all the information for Dunedin to its website as well for a few days which may have also been the cause.

Cheers, love the new tidal feature.

**Comment by ciejer** [comment]
> Also Is there any place we can do requests? I'd love to get some NZ bus timetables in HA as well, could do one of those shout a coffee things

Gosh, certainly wouldn't expect anyone to pay for my shoddy code! The trick with NZ busses would be the lack of cohesion between districts, would assume its another whole API request for every regional council (if not local council)... might be a standalone integration per town...

However, after writing the above I had a bit of a search around to see how hard it would be ;) and it's a solved problem with a standard format and a 1st party HA integration (no GUI config, but you have to upload a .zip so was going to be a bit of a pain) https://www.home-assistant.io/integrations/gtfs
You can get Dunedin GTFS .zip from https://www.orc.govt.nz/privacy-and-tscs
There are no live feeds for that; to get those you'd need to get someone to write a plugin for https://api-doc.transitapp.com/ which services Dunedin - couldn't find anything online for that.
