### ISSUE TITLE
No Air pressure on Port Hills

### ISSUE THREAD

**Issue by nickrout** [ciejer/metservice-weather#55]
## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1404
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 26, 2024 at 12:00 PM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
certificate_status | ready
instance_id | a5d302bea86446178ca241c917807baa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 62.3 GB
disk_used | 11.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), ZeroTier One (0.18.0), Advanced SSH & Web Terminal (17.2.0), Zigbee2MQTT (1.36.0-1), Studio Code Server (5.15.0), Frigate Proxy (1.4), ESPHome (2024.3.0), Mealie (v1.3.2), Samba share (12.3.1), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 13, 2024 at 6:31 PM
-- | --
current_recorder_run | March 23, 2024 at 6:05 PM
estimated_db_size | 420.40 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Loving this new integration, thank you very much.

I am getting neither Air Pressure nor Air Pressure Trend. There are entities created called 
sensor.port_hills_pressure and sensor.port_hills_pressure_tendency_trend, but bith have been "Unknown" since I installed the integration 20 hours ago.

### Reproduction steps

1. Install integration
2. Configure for Port Hills
3. Get no pressure pressure trend
...

### Diagnostics dump

There is no device created in my system and this therefore isn't available.

**Comment by ciejer** [comment]
Hi @nickrout - looks like that feature isn't available for MetService in your area.
See https://www.metservice.com/towns-cities/regions/christchurch/locations/port-hills on the left hand bar - compare to metservice.com/towns-cities/locations/christchurch

A workaround could be creating two integrations?
