### ISSUE TITLE
weather.device_name entity is unavailable

### ISSUE THREAD

**Issue by jedney** [ciejer/metservice-weather#87]
## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4980
Installed Version | 2.0.1
Stage | running
Available Repositories | 1469
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 6, 2025 at 12:00 PM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
cloud_ice_servers_enabled | true
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
instance_id | 5bf1a599c99a48e59324384e44e7f3f2
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 46.5 GB
disk_used | 16.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.17.3), ESPHome Device Compiler (2024.11.2), Let's Encrypt (5.2.5), Samba share (12.3.2), Terminal & SSH (9.15.0), Samba Backup (5.2.0), Mosquitto broker (6.4.1), NGINX Home Assistant SSL proxy (3.11.1), FTP (5.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 33
views | 34
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 21, 2024 at 4:30 AM
-- | --
current_recorder_run | November 30, 2024 at 7:26 PM
estimated_db_size | 946.36 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.24
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 1

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After switching back to the Public API from the Mobile API on v0.8 most entities are populated, except the weather.nz_metservice entity (with forecast information). 

I tried configuring the location as Cambridge, then I tried Hamilton. The same result happened.

I deleted the nz_metservice device I had created from the integration, rebooted and recreated it. No difference.

The entity is correctly created (the device has 21 entities, up from the 19 on the mobile API), but I open the weather.nz_metservice entity it says "This entity is unavailable".

I noticed these two errors in the system logs:

> Logger: homeassistant.components.weather
> Source: helpers/entity_platform.py:599
> integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
> First occurred: 7:26:24 PM (4 occurrences)
> Last logged: 7:31:16 PM
> 
> Error adding entity weather.nz_metservice for domain weather with platform metservice_weather
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
>     self.__async_calculate_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
>     if extra_state_attributes := self.extra_state_attributes:
>                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/metservice_weather/weather.py", line 340, in extra_state_attributes
>     'forecast_daily': self.forecast_daily
>                       ^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/metservice_weather/weather.py", line 424, in forecast_daily
>     for day in range(0, num_days):
>                ^^^^^^^^^^^^^^^^^^
> TypeError: 'NoneType' object cannot be interpreted as an integer

and also:

> Logger: custom_components.metservice_weather.coordinator
> Source: custom_components/metservice_weather/coordinator.py:358
> integration: MetService New Zealand Weather ([documentation](https://github.com/ciejer/metservice-weather), [issues](https://github.com/ciejer/metservice-weather/issues))
> First occurred: 7:26:24 PM (11 occurrences)
> Last logged: 7:34:53 PM
> 
> Error retrieving public forecast daily sensor '' for day 0: 'days'

### Reproduction steps

Install integration v0.8
Create a new device with the name "NZ MetService".
Set town to Cambridge or Hamilton.
Look for the weather.nz_metservice entity in Developer Tools or Device Entity view.
Entity has the error "This entity is unavailable"

**Comment by jeremysherriff** [comment]
Confirming the same issue for me, this is not an isolated case.

For further reports of the same fault, please 👍 the OP rather than commenting a +1 or similar.

**Comment by ciejer** [comment]
Couldn't for the life of me figure this out... works for almost everyone, didn't work for Hamilton...

Turns out that due to a typo, it only worked when Tides were configured, and of course Hamilton doesn't have a tide.
V0.8.1 coming shortly.

**Comment by sultanoswing** [comment]
Heh - same issue for me, living in Palmerston North :)

I found a work around yesterday, which was to use the Mobile API key.

**Comment by ciejer** [comment]
@sultanoswing or others can you confirm v0.8.1 solves for you? It did in my testing

**Comment by jedney** [comment]
Sorry for the delay,  Ive just installed v0.8.1 and it this has fixed the issue for me. Thanks heaps for the quick fix, and for your work on this integration.

**Comment by sultanoswing** [comment]
Fixed it for me, thanks.  Mind you,  I disabled tide info, given I'm in Palmy. Great to have the integration working fully,  as its now powering my Custom Weather Chart Card properly for the first time (so I've been able to stop using Openweather, and don't have to try Weather.com).
